#!/bin/sh
if [ "$1" = "log" ]; then
        cat /var/log/syslog | grep fmberryd
else
        if [ "$1" = "" ] || [ "$1" = "help" ] || [ "$1" = "--help" ]; then
                echo "ctlfmberry usage:"
                echo "  ctlfmberry <tr> set freq 99000 - Frequency in kHz (76000 - 108000)"
                echo "  ctlfmberry <tr> poweron"
                echo "  ctlfmberry <tr> poweroff"
                echo "  ctlfmberry <tr> set rdsid DEADBEEF (8 chars! Longer strings will be truncated, shorter - padded with spaces)"
                echo "  ctlfmberry <tr> set rdstext Mike Oldfield - Pictures (max. 64 chars. Longer strings will be truncated)"
                echo "  ctlfmberry <tr> set rdspi 0x7000 - RDS PI between 0x0000 and 0xFFF. Avoid locally used PI codes"
                echo "  ctlfmberry <tr> set rdspty 10 - RDS program type between 0 and 31"
                echo "  ctlfmberry <tr> set txpwr 0 - 0.5 mW Outputpower"
                echo "  ctlfmberry <tr> set txpwr 1 - 0.8 mW Outputpower"
                echo "  ctlfmberry <tr> set txpwr 2 - 1.0 mW Outputpower"
                echo "  ctlfmberry <tr> set txpwr 3 - 2.0 mW Outputpower (Default)"
                echo "  ctlfmberry <tr> stereo on - Enables stereo signal (Default)"
                echo "  ctlfmberry <tr> stereo off - Disables stereo signal"
                echo "  ctlfmberry <tr> muteon - Mute audio"
                echo "  ctlfmberry <tr> muteoff - Unmute audio"
                echo "  ctlfmberry <tr> gainlow - Audio gain -9dB"
                echo "  ctlfmberry <tr> gainoff - Audio gain 0dB"
                echo "  ctlfmberry <tr> set volume 0-6 Audio volume level 0 to 6, equal -9dB to +9db, 3dB step"
                echo "  ctlfmberry <tr> status - Print current status"
                echo "  ctlfmberry all stop - Stop FMBerry daemon"
                echo "  ctlfmberry log - show logfile for FMBerry"
                echo ""
                echo "  <tr>: specify one or more transmitters (as named in the .conf file) or all for all transmitters"
                echo "  examples: ctlfmberry 0,1 muteon - ctlfmberry 1 gainlow - ctlfmberry all muteoff"
        else
                echo -n "$@"|netcat 127.0.0.1 42516
        fi
fi
